use crate::config::GuardConfig;
use std::path::Path;

use super::{write_config, TranslateError};

/// Generate clamd.conf and freshclam.conf from the [antivirus] config.
pub fn generate(config: &GuardConfig, run_dir: &Path) -> Result<(), TranslateError> {
    let clamav_dir = run_dir.join("clamav");
    std::fs::create_dir_all(&clamav_dir)?;

    let clamd = build_clamd_conf(config);
    write_config(&clamav_dir, "clamd.conf", &clamd)?;

    let freshclam = build_freshclam_conf(config);
    write_config(&clamav_dir, "freshclam.conf", &freshclam)?;

    Ok(())
}

fn build_clamd_conf(config: &GuardConfig) -> String {
    let av = &config.antivirus;

    let log_dir = config
        .guard
        .run_dir
        .join("clamav")
        .join("log")
        .display()
        .to_string();

    let socket_path = config
        .guard
        .run_dir
        .join("clamav")
        .join("clamd.sock")
        .display()
        .to_string();

    let excludes: String = av
        .exclude
        .iter()
        .filter_map(|p| p.to_str())
        .map(|p| format!("ExcludePath {p}"))
        .collect::<Vec<_>>()
        .join("\n");

    let on_access_block = if av.on_access {
        format!(
            r#"
# On-access scanning
OnAccessIncludePath /
OnAccessExcludeUname clamav
OnAccessPrevention yes
OnAccessExtraScanning yes"#
        )
    } else {
        String::new()
    };

    format!(
        r#"# Generated by nexis-guard — do not edit manually

LogFile {log_dir}/clamd.log
LogTime yes
LogSyslog no

LocalSocket {socket_path}

DatabaseDirectory /var/lib/clamav

# Scan settings
MaxScanSize 256M
MaxFileSize 128M
MaxRecursion 16
MaxFiles 10000

# Heuristics (beyond pure signature matching)
HeuristicAlerts yes
HeuristicScanPrecedence yes
AlertBrokenExecutables yes
AlertEncrypted yes
AlertOLE2Macros yes
StructuredDataDetection yes

# Archive scanning
ScanArchive yes
ScanPE yes
ScanELF yes
ScanPDF yes
ScanHTML yes
ScanMail yes

{excludes}
{on_access_block}
"#,
        log_dir = log_dir,
        socket_path = socket_path,
        excludes = excludes,
        on_access_block = on_access_block,
    )
}

fn build_freshclam_conf(config: &GuardConfig) -> String {
    let log_dir = config
        .guard
        .run_dir
        .join("clamav")
        .join("log")
        .display()
        .to_string();

    let checks_per_day = interval_to_checks_per_day(&config.antivirus.update_interval);

    format!(
        r#"# Generated by nexis-guard — do not edit manually

DatabaseDirectory /var/lib/clamav
UpdateLogFile {log_dir}/freshclam.log

DatabaseMirror database.clamav.net

# How often to check for updates (times per day)
Checks {checks_per_day}

# Notify clamd after a successful update
NotifyClamd {clamd_conf}
"#,
        log_dir = log_dir,
        checks_per_day = checks_per_day,
        clamd_conf = config
            .guard
            .run_dir
            .join("clamav")
            .join("clamd.conf")
            .display(),
    )
}

/// Convert interval strings like "6h", "12h", "1h" to freshclam's Checks value
/// (number of checks per 24 hours).
fn interval_to_checks_per_day(interval: &str) -> u32 {
    let trimmed = interval.trim_end_matches('h');
    match trimmed.parse::<u32>() {
        Ok(hours) if hours > 0 => 24 / hours,
        _ => 4, // default: every 6 hours
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_interval_conversion() {
        assert_eq!(interval_to_checks_per_day("6h"), 4);
        assert_eq!(interval_to_checks_per_day("12h"), 2);
        assert_eq!(interval_to_checks_per_day("1h"), 24);
        assert_eq!(interval_to_checks_per_day("24h"), 1);
        assert_eq!(interval_to_checks_per_day("garbage"), 4);
    }
}
